#include "pch.h"
#include "VertexType.h"

// 정적 멤버 변수는 클래스 외부에서 초기화
std::vector<D3D11_INPUT_ELEMENT_DESC> Vertex::descs
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0,
	  D3D11_INPUT_PER_VERTEX_DATA, 0 }
};

std::vector<D3D11_INPUT_ELEMENT_DESC> VertexColor::descs
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0,
	  D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0,
	  D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 }
};

std::vector<D3D11_INPUT_ELEMENT_DESC> VertexTexture::descs
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0,
	  D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0,
	  D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 }
};